<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Active' => '啟用',
    'Admin' => '管理員',
    'Super Admin' => '超級管理員',
    'Website Admin' => '網站管理員',
    'Allow' => '允許',
    'Blog' => 'Blog',
    'Can' => '可以',
    'Cannot' => '不可以',
    'Deactivate' => '停用',
    'Disabled' => '停用',
    'Enabled' => '啟用',
    'File List' => '檔案列表',
    'Link' => '連結',
    'Menu Level1' => '第一層',
    'Menu Level2' => '第二層',
    'No' => '否',
    'Not Allowed' => '不允許',
    'Page' => '頁',
    'User' => '普通用戶',
    'Yes' => '是',
    'Checkout done' => '已完成結賬',
    'Checkout form submitted' => '已完成結賬訂單',
    'Checkout processing' => '結賬處理中',
    'Checkout submitted' => '結賬已提交',
    'Order submitted' => '已提交訂單',
    'Payment processing' => '付款處理中',
    'Shipped' => '已發貨',
    'Shopping' => '購物中',
    'To be shipped' => '待送貨',
    'Confirmed' => '已確認',
    'Online payment failed' => '網上付款失敗',
    'Online payment processing' => '網上付款處理中',
    'Credit cart payment failed' => '信用卡付款失敗',
    'Credit cart payment processing' => '信用卡付款處理中',
    'Finish' => '已完成',
    'Canceled' => '已取消',
    'In delivery' => '送貨中',
    'Waiting for confirmation' => '待確認',
    'Waiting for process' => '待處理',
    'Waiting for Direct Bank-in' => '等候銀行入數',
    'Waiting for Direct Bank-in confirmation' => '等候銀行入數確認',
    'Online payment failed' => '網上付款失敗',
    'Online payment processing' => '網上付款處理中',
    'Member' => '普通用戶',
];
