<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Central and Western' => '中西區',
    'Eastern' => '東區',
    'Hong Kong Island' => '香港島',
    'Islands' => '離島區',
    'Kowloon' => '九龍',
    'Kowloon City' => '九龍城區',
    'Kwai Tsing' => '葵青區',
    'Kwun Tong' => '觀塘區',
    'New Territories' => '新界',
    'North' => '北區',
    'Sai Kung' => '西貢區',
    'Sha Tin' => '沙田區',
    'Sham Shui Po' => '深水埗區',
    'Southern' => '南區',
    'Tai Po' => '大埔區',
    'Tsuen Wan' => '荃灣區',
    'Tuen Mun' => '屯門區',
    'Wan Chai' => '灣仔區',
    'Wong Tai Sin' => '黃大仙區',
    'Yau Tsim Mong' => '油尖旺區',
    'Yuen Long' => '元朗區',
];
