<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Payment Method' => '付款方式',
    'Invoice Number' => '賬單編號',
    'Token' => 'Token',
    'URL' => '網址',
    'Note' => '紀錄',
    'Reference Code' => '參考編號',
    'PayPal' => 'PayPal',
    'PayPal (Subscriptions)' => 'PayPal（自動付款）',
    'PPS' => '繳費靈',
    'AlipayHK' => '支付寶HK',
    'Faster Payment System (FPS)' => '轉數快（FPS）',
    'Start' => '開始',
    'Waiting for complete' => '等待完成',
    'Done' => '完成',
    'Cancel' => '取消',
    'Fail' => '失敗',
];
