<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '{0}:' => '{0}：',
    'Home' => '主頁',
    'Contact Us' => '聯絡我們',
    'Address' => '聯絡地址',
    'Phone' => '聯絡電話',
    'Fax' => '傳真號碼',
    'Email' => '聯絡電郵',
    'Website' => '聯絡網址',
    'Name' => '聯絡人',
    'Message' => '查詢內容',
    'Address: {0}' => '聯絡地址：{0}',
    'Contact' => '聯絡我們',
    'Email: {0}' => '聯絡電郵：{0}',
    'Font' => '字體',
    'Telephone: {0}' => '聯絡電話：{0}',
    'Thank you for your inquiry.' => '謝謝你的查詢。',
    'Please fill in the form' => '或填寫以下表格',
    'Detail' => '詳情',
    'Latest Events' => '最新活動',
    'Online Shop' => '網上購物',
    'Temple Service' => '廟宇服務',
    'Member Login' => '會員登入',
    'Subscribe eNews' => '訂閱電子報',
];
