<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Active' => '启用',
    'Admin' => '管理员',
    'Allow' => '允许',
    'Blog' => 'Blog',
    'Can' => '可以',
    'Cannot' => '不可以',
    'Deactivate' => '停用',
    'Disabled' => '停用',
    'Enabled' => '启用',
    'File List' => '档案列表',
    'Link' => '连结',
    'Menu Level1' => '第一层',
    'Menu Level2' => '第二层',
    'No' => '否',
    'Not Allowed' => '不允许',
    'Page' => '页',
    'User' => '普通用户',
    'Yes' => '是',
];
