<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Central and Western' => '中西区',
    'Eastern' => '东区',
    'Hong Kong Island' => '香港岛',
    'Islands' => '离岛区',
    'Kowloon' => '九龙',
    'Kowloon City' => '九龙城区',
    'Kwai Tsing' => '葵青区',
    'Kwun Tong' => '观塘区',
    'New Territories' => '新界',
    'North' => '北区',
    'Sai Kung' => '西贡区',
    'Sha Tin' => '沙田区',
    'Sham Shui Po' => '深水埗区',
    'Southern' => '南区',
    'Tai Po' => '大埔区',
    'Tsuen Wan' => '荃湾区',
    'Tuen Mun' => '屯门区',
    'Wan Chai' => '湾仔区',
    'Wong Tai Sin' => '黄大仙区',
    'Yau Tsim Mong' => '油尖旺区',
    'Yuen Long' => '元朗区',
];