<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '{0}:' => '{0}：',
    'Home' => '主页',
    'Contact Us' => '联络我们',
    'Address' => '联络地址',
    'Phone' => '联络电话',
    'Fax' => '传真号码',
    'Email' => '联络电邮',
    'Website' => '联络网址',
    'Name' => '联络人',
    'Message' => '查询内容',
    'Address: {0}' => '联络地址：{0}',
    'Contact' => '联络我们',
    'Email: {0}' => '联络电邮：{0}',
    'Font' => '字体',
    'Telephone: {0}' => '联络电话：{0}',
    'Thank you for your inquiry.' => '谢谢你的查询。',
    'Please fill in the form' => '或填写以下表格',
    'Detail' => '详情',
    'Latest Events' => '最新活动',
    'Online Shop' => '网上购物',
    'Temple Service' => '庙宇服务',
    'Member Login' => '会员登入',
];
